### ISSUE TITLE
Why sys.excepthook for all (even "control flow" errors) ?

### ISSUE THREAD

**Issue by elnygren** [graphql-python/graphql-core-legacy#142] opened 2017-10-10 13:38 UTC
Hi! I've got some testcases covering invalid mutations e.g mutating a non-existent object with an invalid UUIDv4. GraphQL and graphene handle these quite nicely (user gets a proper error message). 

However, my stderr is still full of errors when I run my tests (that all pass). I did some digging with the debugger and found this line: https://github.com/graphql-python/graphql-core/blob/f8a6a8a27119f924c2fce863cca87c4219d8a12b/graphql/execution/base.py#L85

Why do we want to print everything to stderr?

**manage.py test output**

```
python manage.py test --settings=config.test_settings
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..Traceback (most recent call last):
  File "/Users/elnygren/Work/sumpli/sumpli-core/ENV/lib/python3.6/site-packages/graphql/execution/executor.py", line 215, in complete_value_catching_error
    exe_context, return_type, field_asts, info, result)
  File "/Users/elnygren/Work/sumpli/sumpli-core/ENV/lib/python3.6/site-packages/graphql/execution/executor.py", line 268, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: No Business matches the given query.
.Traceback (most recent call last):
  File "/Users/elnygren/Work/sumpli/sumpli-core/ENV/lib/python3.6/site-packages/graphql/execution/executor.py", line 215, in complete_value_catching_error
    exe_context, return_type, field_asts, info, result)
  File "/Users/elnygren/Work/sumpli/sumpli-core/ENV/lib/python3.6/site-packages/graphql/execution/executor.py", line 268, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: 'foo-bar-xyz-abc' is not a valid UUID.
.....................................
```

Note that: 

> No Business matches the given query.  

and

> 'foo-bar-xyz-abc' is not a valid UUID.

are the messages shown to the users.

**Code**

```python
class LikeABusiness(graphene.Mutation):
    """Mutation for liking/following a Business."""
    class Arguments:
        """Arguments of the Mutation"""
        uuid = graphene.String(required=True)

    # output
    ok = graphene.Boolean()

    def mutate(self, info, uuid, *args, **kwargs):
        """Perform the data mutation."""
        try:
            # raises the "No Business matches the given query." message due to 404
            return LikeABusiness(
                ok=get_object_or_404(Business, uuid=uuid).like(info.context.user)
            )
        except ValidationError as e:
            # passes along the "'foo-bar-xyz-abc' is not a valid UUID." message
            raise Exception(e.messages[0])
```

**Comment by janosroden** [comment] 2017-11-22 17:20
I'm new in python, but I think this is the cause of the "Press Enter to continue" message during debugging such a test.

**Comment by zyguan** [comment] 2017-12-04 06:13
That's annoying! Can we make the error reporting configurable? eg. add an additional callback arg to [ExecutionContext](https://github.com/graphql-python/graphql-core/blob/6df8a6312b579a6a1454bcf29a566ce5d0fa9849/graphql/execution/base.py#L24) and [execute](https://github.com/graphql-python/graphql-core/blob/6df8a6312b579a6a1454bcf29a566ce5d0fa9849/graphql/execution/executor.py#L31) or just allow us to pass the custom context class to the execute function.

**Comment by mariogarcia** [comment] 2017-12-05 08:55
I've found a possible solution, at least for middlewares:

I've created an authentication middleware and I had the same problem. It was very annoying getting stacktraces every time a user failed to authenticate.

Looking into this I realized that tests regarding middlewares were using `promises`, so I thought what would happen if I returned `Promise.reject(GraphQLError('message'))` from my middleware instead or raising the error. 

It turned out to be the solution, it shows the graphql error to the user and it's logged as a single error line by the application logging system. No more stacktraces everywhere.

I hope this helps

**Comment by elnygren** [comment] 2017-12-05 12:53
@mariogarcia after your trick my

```
python manage.py test --settings=config.test_settings
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..Traceback (most recent call last):
  File "/Users/elnygren/Work/sumpli/sumpli-core/ENV/lib/python3.6/site-packages/graphql/execution/executor.py", line 215, in complete_value_catching_error
    exe_context, return_type, field_asts, info, result)
  File "/Users/elnygren/Work/sumpli/sumpli-core/ENV/lib/python3.6/site-packages/graphql/execution/executor.py", line 268, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: No Business matches the given query.
.Traceback (most recent call last):
  File "/Users/elnygren/Work/sumpli/sumpli-core/ENV/lib/python3.6/site-packages/graphql/execution/executor.py", line 215, in complete_value_catching_error
    exe_context, return_type, field_asts, info, result)
  File "/Users/elnygren/Work/sumpli/sumpli-core/ENV/lib/python3.6/site-packages/graphql/execution/executor.py", line 268, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: 'foo-bar-xyz-abc' is not a valid UUID.
.....................................
```

turned into

```
python manage.py test --settings=config.test_settings
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..graphql.error.located_error.GraphQLLocatedError: No Brand matches the given query.
.graphql.error.located_error.GraphQLLocatedError: 'foo-bar-xyz-abc' is not a valid UUID.
........................................
```

So a little less verbose but still unnecessary printing of errors somewhere....


Code:
```
    except ValidationError as e:
        return Promise.reject(GraphQLError(e.messages[0]))
```

**Comment by mariogarcia** [comment] 2017-12-05 15:24
Well in my case I think is still desirable to have a minimum traceability of authentication errors. 

But yeah, I think you're right, maybe there should be a specific type of error that `graphql-core` could propagate without being verbose along the way. Or maybe a flag in the `GraphQLError` type:

Special type:

```Python
Promise.reject(GraphQLUserError('message'))
```
or flag:

```Python
Promise.reject(GraphQLError(message='message', log=False))
```

**Comment by zyguan** [comment] 2017-12-06 15:55
@elnygren If you do not wanna see any annoying output, you can actually overwrite the `sys.excepthook`, eg. put the following code to your setup function.
```python
sys.excepthook = lambda *_: None
```
However it's not a good idea to ignore all exceptions. So you may use an custom exception to specify which you want to ignore.
```python
class AppWarning(Exception):
    pass


def app_excepthook(t, e, tb):
    if isinstance(e, GraphQLLocatedError) and \
            isinstance(e.original_error, AppWarning):
        return  # or put a warning msg if you want
    else:
        logging.error('Uncaught error: %s', e, exc_info=(t, e, tb))

sys.excepthook = app_excepthook
```
In my humble opinion, you'd better set `stack` attribute to all errors caught by you logic code (and then reject them) so that the important traceback info won't be discard by [GraphQLLocatedError](https://github.com/graphql-python/graphql-core/blob/cece343f05e9517ac244433586ccabaea92f1bb1/graphql/error/located_error.py#L19). eg:
```python
try:
    # your logic code here
except Exception as e:
    if not hasattr(e, 'stack'):
        _, _, tb = sys.exc_info()
        setattr(e, 'stack', tb)
    return Promise.reject(e)
```

**Comment by CaselIT** [comment] 2017-12-19 09:37
I think that the best option would be to use the logging library to log the error instead of `sys.excepthook`, so the user of the library has full control on what should be reported.

**Comment by CaselIT** [comment] 2017-12-19 18:44
I've added a [PR](https://github.com/graphql-python/graphql-core/pull/154) to close this issue.

**Comment by charettes** [comment] 2018-01-19 22:11
Thanks for the PR @CaselIT, I also agreed that `logger.exception` is a way better option that `sys.excepthook` to propagate these errors.

**Closed as completed** 2018-01-21 07:56 UTC

**Comment by tlinhart** [comment] 2018-03-17 06:50
@CaselIT @charettes Guys, how does this solve the original problem? Say I want to be able to selectively control which exceptions should only result in error messages in the output and which should also be logged (possibly with stack trace) for later debugging. The former could be a case for business logic errors in resolvers (e.g. authentication/authorization errors). The later could stem from uncaught exceptions or exceptions deliberately left to propagate (e.g. failed database reads or external API calls).

Is there a way to control this behaviour? `sys.excepthook` at least provided a way to solve this but I'm not sure how to do it when exceptions are logged.

**Comment by charettes** [comment] 2018-03-17 06:56
@tlinhart isn't this something you can achieve with logging filters and handlers?

**Comment by tlinhart** [comment] 2018-03-17 07:06
@charettes I'm not sure, could you provide an example? Say that all business errors would result in `BusinessError` exception raised. (I would raise this exception directly or wrap any other exception.) These should only result in errors in GraphQL response. All others should also be logged. I can't think of an easy and convenient way to achive this.

**Comment by CaselIT** [comment] 2018-03-17 09:20
@tlinhart as @charettes has proposed I think you can handle it with logging filters.
Something like
```py
class Filter(logging.Filter):
    def filter(self, record):
        return 'BusinessError' not in record.msg

logging.getLogger('graphql.execution.base').addFilter(Filter())
```

**Comment by tlinhart** [comment] 2018-03-17 09:51
@CaselIT Thanks for an example. I agree it's theoretically doable, but I really don't find this the best solution. One reason is that it's unnecessary overhead. The second reason is that filtering based on a text pattern is ugly, hard to maintain and very error prone. In this light, I find `sys.excepthook` solution the better one. What do you think?

**Comment by CaselIT** [comment] 2018-03-17 10:29
I disagree. I think that a library should avoid logging to standard error by default and instead use the logging library, so the users can easily customize the behavior.

Regarding what you are trying to accomplish, I agree that it's not the best solution the one that I have proposed. I'm opening a new pr to make filtering easier by using the kwarg argument `exc_info` in the logging call

**Comment by tlinhart** [comment] 2018-03-17 10:43
I totally agree on the first point. Regarding the second, could you please reference this issue in the PR do tracking is easier?

**Comment by CaselIT** [comment] 2018-03-17 10:46
@tlinhart it's now open

**Comment by mariogarcia** [comment] 2018-03-18 11:19
BTW, I would like to share my recent experience handling errors with `graphq-java` which I believe is the reference in the JVM world. 

**Error vs Exception**

When using this library, I always try to separate what is an `error` of what is an `exception`. The framework itself sometimes mixes errors and exceptions, but I think there's a simple rule that could be used from the developer point of view that could help when deciding what error policy to apply.

- An `error` is just a data structure carrying data used to rendered as an error as a result of a given business logic. An error it's not returned as result but added to the current execution context errors. That enables all use cases, even the rare use case of having a result with data and errors.

- Whereas an `exception` is a non expected behavior that happens to be rendered as an `error` with the extra information of the exception's stacktrace. When an exception is thrown, the current execution is interrupted and, by default you can see the stacktrace in the logs, because is a non expected behavior. The appealing part of exceptions is that you may think of exceptions as a way of returning an error every time you don't want to return a result. And that's not the best way of building your business logic. At least in the Java world an stacktrace has a given execution cost that a simple data structure doesn't have. That's why `errors` as data are better than **throwing** exceptions. 

If you would like to handle certain situations and send an error back you should be sending an `error` which is an expected result of a certain business logic.

**Error extensions**

An `error` has pretty much the same structure of an exception

- message
- location
- path

But it also has an `extensions` attribute that could be used to add extra information to the current error.

I hope this helps
Mario

**Comment by elnygren** [comment] 2018-08-26 15:09
Thans for everyone involved in the fix! Indeed, using `logging` is much better than `sys.excepthook` 

@tlinhart as you can see from the PR, the logger is created as `logger = logging.getLogger(__name__)`. The `__name__` is relevant for deciding whether the logged entry will show up in your final errors logs (and/or console stdout/stderr). To learn how this is done, refer to any python `logging` module tutorial. 

Essentially you can tell that a logger of certain level has a certain log level, format, output (eg. file or stdout) etc.
